lib/chat_app_web/router.ex
defmodule ChatAppWeb.Router do
  use ChatAppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ChatAppWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatAppWeb do
    pipe_through :browser

    get "/", RoomController, :index
    resources("/rooms", RoomController, except: [:index])
    resources("/sessions", SessionController, only: [:new, :create])
    delete "/sign_out", SessionController, :delete
    resources("/registration", RegistrationController, only: [:new, :create])
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatAppWeb do
  #   pipe_through :api
  # end
end

lib/chat_app_web/views/layout_view.ex
defmodule ChatAppWeb.LayoutView do
  use ChatAppWeb, :view
end

lib/chat_app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ChatApp · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-dark">
      <h3 class="my-0 mr-md-auto font-weight-normal">
        <%= link "Chat App", to: Routes.room_path(@conn, :index), class: "navbar-brand text-highlight" %>
      </h3>
      <%= if @signed_in? do %>
        <nav class="text-light my-2 my-md-0 mr-md-3">
          Signed in as: <strong><%= ChatApp.Accounts.current_user(@conn).username%></strong>
        </nav>
        <%= link "Sign Out", to: Routes.session_path(@conn, :delete), method: :delete, class: "btn btn-outline-primary" %>
      <% else %>
        <%= link "Sign In", to: Routes.session_path(@conn, :new), class: "btn btn-outline-primary ml-md-3" %>
        <%= link "Sign Up", to: Routes.registration_path(@conn, :new), class: "btn btn-outline-primary ml-md-3" %>
      <% end %>
    </div>
    
    <%= unless is_nil(get_flash(@conn, :info)) do %>
      <div class="alert alert-info alert-dismissible" role="alert"><%= get_flash(@conn, :info) %></div>
    <% end %>
    <%= unless is_nil(get_flash(@conn, :error)) do %>
      <div class="alert alert-danger alert-dismissible" role="alert"><%= get_flash(@conn, :error) %></div>
    <% end %>
    <main role="main" class="container">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>